import "~/styles/globals.css";

import { type Metadata } from "next";
import localFont from "next/font/local";

import { TRPCReactProvider } from "~/trpc/react";
import { Provider } from "~/components/provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const font = localFont({
  src: "../../public/fonts/radikal-regular.otf",
  variable: "--font-radikal-regular",
});

const nikeFont = localFont({
  src: "../../public/fonts/futura-bold.ttf",
  variable: "--font-future-bold",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${font.variable} ${nikeFont.variable} font-sans`}
    >
      <body>
        <TRPCReactProvider>
          <Provider>{children}</Provider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
